<!DOCTYPE html>
<html lang="en">
<head>
    <title>DBT - Centre for Microbial Informatics</title>
    <?php include_once 'head_links.php';
    include 'log.php' ?>
    <?php $page = "home" ?>
</head>
<body>
    <div class="wave bg-white">
        <img src="images/wave_dpurple2.svg" alt="Background Wave">
    </div>
    
    <!-- Navbar -->
    <?php include_once 'navbar.php'; ?>
    
    <!-- Main Content -->
    
    <div class="container-fluid mainContent">
        <main class="container pb-5 mt-5">
            <!-- Header -->
            <div class="row align-items-center g-5 py-5 my-5 text-white">
                <div class="col-lg-6 shadow-lg p-5 bg-primary text-uppercase mx-auto">
                    <h1 class="display-5 fw-bold lh-1">DBT-CMI</h1>
                    <h4 class="lh-1 text-light">Department of Biotechnology</h4>
                    <h3 class="fw-bold lh-1 mb-2">Centre for Microbial Informatics</h3>
                    <p>School of Life Sciences, University of Hyderabad</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href="#about" type="button" class="btn btn-primary px-4 me-md-2">Know More <i class="bi bi-arrow-down-circle"></i></a>
                    </div>
                </div>
                <!-- Image -->
                <div class="col-lg-6 mx-auto bannerImg">
                    <img src="images/microbiota_1sm.png" class="d-block w-100 mx-lg-auto img-fluid" alt="Bootstrap Themes">
                    <p class="text-end text-secondary">Image generated by <a href="https://midjourney.com/home/?callbackUrl=%2Fapp%2F" target="_blank" class="text-warning">MidJourney</a> AI</p>
                    <!-- Carousel without indicators 
                    <div id="myCarousel" class="carousel carousel-fade" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="images/microbiota_1sm.png" class="d-block w-100 mx-lg-auto img-fluid" alt="Bootstrap Themes">
                            </div>
                            <div class="carousel-item">
                                <img src="images/microbiota_2sm.png" class="d-block w-100 mx-lg-auto img-fluid" alt="Bootstrap Themes">
                            </div>
                            <div class="carousel-item">
                                <img src="images/microbiota_3sm.png" class="d-block w-100 mx-lg-auto img-fluid" alt="Bootstrap Themes">
                            </div>
                        </div>
                    </div>-->
                </div>
            </div>
        </main>
    </div>
    
    
    <section id="about">
        <div class="container py-5 mt-5">
            <h3 class="pb-2 text-uppercase"><?php echo $_SERVER['PHP_SELF'] ?></h3>
            <hr class="w-50">
            <div class="row row-cols-1 row-cols-lg-2 align-items-md-center g-5 pb-5">
                <div class="col d-flex flex-column align-items-start gap-2">
                    <p class="text-muted">
                        INDIA with its diverse populations, climatic conditions, environments and associated habitats, could be considered as a <mark>mini Earth</mark> <i class="bi bi-globe-central-south-asia text-success"></i>, forming a hotspot for the exploration of bacterial genomes and metagenomes.
                        <br>
                        <span class="fw-bold fs-5 text-primary">DBT-CMI</span> is an integrated <mark>"one-stop-portal" for niche-specific microbial informatics of India</mark> with information on the biotechnological potential of microbes. This portal will be a hub for scientists, industry and policymakers to develop sustainable microbial technologies required for the nation. Availability of such a gamut of information will help in:
                        <ul class="text-muted">
                            <li>the use of microbes in agriculture for enhancing crop production is an emerging alternative to chemical fertilizers and pesticides. Microbiome analysis centre to support in interpretation of the sequencing data pertaining to plants and soil specifically to understand the ecological aspects, molecular interactions with respect to microbiome function.</li>
                            <li>understanding rhizosphere microbial dynamics and their implications in plant health and yield can be assessed for sustainable agriculture. Similarly microbiome analysis for seeds would unlock doors for microbiome assisted breeding strategies towards nutrition enhanced foods.</li>
                            <li>the microbiome studies specifically targeted toward evaluation for pathogen screening studies, dynamics of artificial syn-communities to improve the yield of plants, inter-cropping studies, pesticide and fertilizer effect on the natural crop land ecosystems etc.</li>
                        </ul>
                    </p>
                    <a href="research.php" class="btn btn-primary">Research <i class="bi bi-arrow-right-circle"></i></a>
                </div>
                <!-- Column List -->
                <div class="col">
                    <div class="special-list-item p-3 rounded mr-0 me-lg-4">
                        <div class="d-block d-sm-flex align-items-center m-2">
                            <div class="icon me-4 mb-4 mb-sm-0 bg-info shadow"> 
                                <i class="bi bi-calendar2-check-fill mt-4" style="font-size:36px"></i>
                            </div>
                            <div class="block">
                                <h4 class="mb-3">Upcoming Events</h4>
                                <p class="mb-0 text-muted">
                                    Workshops: 
                                    <a href="events.php#jan2023">Genomics 2023</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="special-list-item p-3 rounded mr-0 me-lg-4">
                        <div class="d-block d-sm-flex align-items-center m-2">
                            <div class="icon me-4 mb-4 mb-sm-0 bg-accent3 shadow"> 
                                <i class="bi bi-database-check mt-4" style="font-size:36px"></i>
                            </div>
                            <div class="block">
                                <h4 class="mb-3">Database Collections</h4>
                                <a href="databases.php">
                                    <p class="mb-0">Populating...</p>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="special-list-item p-3 rounded mr-0 me-lg-4">
                        <div class="d-block d-sm-flex align-items-center m-2">
                            <div class="icon me-4 mb-4 mb-sm-0 bg-success opacity-50 shadow"> 
                                <i class="bi bi-code-slash mt-4" style="font-size:36px"></i>
                            </div>
                            <div class="block">
                                <h4 class="mb-3">Pipelines & Tools</h4>
                                <a href="pipelines.php">
                                    <p class="mb-0">Under Development...</p>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="special-list-item p-3 rounded mr-0 me-lg-4">
                        <div class="d-block d-sm-flex align-items-center m-2">
                            <div class="icon me-4 mb-4 mb-sm-0 bg-danger opacity-50 shadow"> 
                                <i class="bi bi-pc-display mt-4" style="font-size:36px"></i>
                            </div>
                            <div class="block">
                                <h4 class="mb-3">Services</h4>
                                <a href="services.php">
                                    <p class="mb-0">Launching Soon...</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Footer -->
    <?php include_once 'footer.php'; ?>
    
</body>
</html>